
package msc.ws.sesion5;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CatalogoITESOService", targetNamespace = "http://sesion5.ws.msc/", wsdlLocation = "http://tkgdl-116.tacitknowledge.com:8080/Sesion7/CatalogoITESOService?wsdl")
public class CatalogoITESOService
    extends Service
{

    private final static URL CATALOGOITESOSERVICE_WSDL_LOCATION;
    private final static WebServiceException CATALOGOITESOSERVICE_EXCEPTION;
    private final static QName CATALOGOITESOSERVICE_QNAME = new QName("http://sesion5.ws.msc/", "CatalogoITESOService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://tkgdl-116.tacitknowledge.com:8080/Sesion7/CatalogoITESOService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CATALOGOITESOSERVICE_WSDL_LOCATION = url;
        CATALOGOITESOSERVICE_EXCEPTION = e;
    }

    public CatalogoITESOService() {
        super(__getWsdlLocation(), CATALOGOITESOSERVICE_QNAME);
    }

    public CatalogoITESOService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CATALOGOITESOSERVICE_QNAME, features);
    }

    public CatalogoITESOService(URL wsdlLocation) {
        super(wsdlLocation, CATALOGOITESOSERVICE_QNAME);
    }

    public CatalogoITESOService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CATALOGOITESOSERVICE_QNAME, features);
    }

    public CatalogoITESOService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CatalogoITESOService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CatalogoITESO
     */
    @WebEndpoint(name = "CatalogoITESOPort")
    public CatalogoITESO getCatalogoITESOPort() {
        return super.getPort(new QName("http://sesion5.ws.msc/", "CatalogoITESOPort"), CatalogoITESO.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CatalogoITESO
     */
    @WebEndpoint(name = "CatalogoITESOPort")
    public CatalogoITESO getCatalogoITESOPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sesion5.ws.msc/", "CatalogoITESOPort"), CatalogoITESO.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CATALOGOITESOSERVICE_EXCEPTION!= null) {
            throw CATALOGOITESOSERVICE_EXCEPTION;
        }
        return CATALOGOITESOSERVICE_WSDL_LOCATION;
    }

}
