
package msc.ws.sesion5;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CatalogoITESO", targetNamespace = "http://sesion5.ws.msc/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CatalogoITESO {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "agregarMaterias", targetNamespace = "http://sesion5.ws.msc/", className = "msc.ws.sesion5.AgregarMaterias")
    @ResponseWrapper(localName = "agregarMateriasResponse", targetNamespace = "http://sesion5.ws.msc/", className = "msc.ws.sesion5.AgregarMateriasResponse")
    @Action(input = "http://sesion5.ws.msc/CatalogoITESO/agregarMateriasRequest", output = "http://sesion5.ws.msc/CatalogoITESO/agregarMateriasResponse")
    public boolean agregarMaterias(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerMateriasPorCategoria", targetNamespace = "http://sesion5.ws.msc/", className = "msc.ws.sesion5.ObtenerMateriasPorCategoria")
    @ResponseWrapper(localName = "obtenerMateriasPorCategoriaResponse", targetNamespace = "http://sesion5.ws.msc/", className = "msc.ws.sesion5.ObtenerMateriasPorCategoriaResponse")
    @Action(input = "http://sesion5.ws.msc/CatalogoITESO/obtenerMateriasPorCategoriaRequest", output = "http://sesion5.ws.msc/CatalogoITESO/obtenerMateriasPorCategoriaResponse")
    public List<String> obtenerMateriasPorCategoria(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<msc.ws.sesion5.Materia>
     * @throws EntradaInvalida_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerListaMateriasPorCategoria", targetNamespace = "http://sesion5.ws.msc/", className = "msc.ws.sesion5.ObtenerListaMateriasPorCategoria")
    @ResponseWrapper(localName = "obtenerListaMateriasPorCategoriaResponse", targetNamespace = "http://sesion5.ws.msc/", className = "msc.ws.sesion5.ObtenerListaMateriasPorCategoriaResponse")
    @Action(input = "http://sesion5.ws.msc/CatalogoITESO/obtenerListaMateriasPorCategoriaRequest", output = "http://sesion5.ws.msc/CatalogoITESO/obtenerListaMateriasPorCategoriaResponse", fault = {
        @FaultAction(className = EntradaInvalida_Exception.class, value = "http://sesion5.ws.msc/CatalogoITESO/obtenerListaMateriasPorCategoria/Fault/EntradaInvalida")
    })
    public List<Materia> obtenerListaMateriasPorCategoria(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws EntradaInvalida_Exception
    ;

}
